build:
  version: "1.0"

cards:
  message: "Welcome to EazyBank cards related to prod APIs"
  contactDetails:
    name: "Akshay Jangwal - Product Owner"
    email: "akshayjangwal@gmail.com"
  onCallSupport:
    - (777) 777-5678
    - (777) 723-0066