spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

cards:
  message: "Welcome to EazyBank cards related to QA APIs"
  contactDetails:
    name: "Anshul Jangwal - QA Tester"
    email: "anshuljangwal@gmail.com"
  onCallSupport:
    - (666) 666-9876
    - (666) 623-5431