spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

loans:
  message: "Welcome to EazyBank loans related to prod APIs"
  contactDetails:
    name: "MS Dhoni - Product Owner"
    email: "mahi@gmail.com"
  onCallSupport:
    - (666) 666-8787
    - (666) 666-7453